Repository tengattack/unified-ci, pull requests merged in 2018-10, with the labels that each got.

#4 Add cpplint
  checker/lint.go
  checker/message.go
  checker/message_test.go
  config.example.yaml
  config/config.go
  tests/sillycode.cpp
  tests/sillycode.cpp.diff
Labels: feature

#5 Add cli command
  config/config.go
  main.go
Labels: feature

#7 Add README
  README.md
Labels: feature

#8 Fix duplicated messages
  checker/github.go
Labels: bug

#10 Add missing output log
  .gitignore
  checker/lint.go
Labels: enhancement
