Repository tengattack/unified-ci, pull requests merged in 2019-11, with the labels that each got.

#71 Add testdata/markdown/package.json
  checker/message_test.go
  testdata/markdown/package.json
Labels: enhancement, size/S

#70 Fix lint options of APIDoc
  checker/lint.go
  checker/lint_test.go
  testdata/go/apidoc.json
Labels: bug, size/M

#69 Add lints-ignore path patterns to projects config
  .unified-ci.yml
  checker/lint.go
  checker/message.go
  checker/message_test.go
  checker/utils.go
  checker/utils_test.go
Labels: enhancement, size/L

#72 Add master branch check & badges
  README.md
  checker/github.go
  checker/github_test.go
  checker/gotest.go
  checker/message.go
  checker/server.go
  store/store.go
  store/store_test.go
  testdata/test1.go
Labels: size/XL
