Repository tengattack/unified-ci, pull requests merged in 2020-10, with the labels that each got.

#93 Update test private key & webhook secret config
  checker/handler.go
  common/github_test.go
  config.example.yml
  config/config.go
  testdata/config.yml
  testdata/unified-ci-test.2019-07-09.private-key.pem
  testdata/unified-ci-test.2020-10-11.private-key.pem
Labels: enhancement, size/M

#94 checks/lint: 没有 tslint 配置时尝试用 eslint 检查
  checks/lint/lint.go
Labels: size/S

#95 Add concurrency queue support
  Makefile
  checker/queue.go
  checks/lint/linters.go
  config.example.yml
  config/config.go
  main.go
  mq/mq.go
  mq/redis/redis.go
Labels: feature, size/L
