Repository tengattack/unified-ci, pull requests merged in 2020-03, with the labels that each got.

#78 Logging into file directly when running one single test
  checker/gotest.go
  checker/gotest_test.go
  checker/message.go
  go.mod
  go.sum
Labels: enhancement, size/L

#79 Add jwt client proxy support
  main.go
  util/roundtripper.go
Labels: size/S

#80 Add file mode check
  checker/lint.go
  checker/lint_test.go
  checker/message.go
  checker/utils.go
  checker/utils_test.go
  testdata/lines
  testdata/src/a
  testdata/src/b.py
  testdata/src/c.sh
  testdata/src/d.sh
  testdata/src/e.sh
  testdata/src/f.py
  testdata/src/g.py
  testdata/src/h.py
  testdata/src/src.diff
Labels: feature, size/L

#81 Fix the bug of CheckFileMode of missing annotations
  checker/message.go
Labels: bug, size/XS
